Update Ember tree

diff --git a/rubberfs b/rubberfs
--- a/rubberfs
+++ b/rubberfs
@@ -18,18 +18,18 @@ create)
     #TODO: Check for pending jobs all done: curl "http://s3.us.archive.org/?check_limit=1&accesskey=$accessKey&bucket=$identifier"
     s3backer --accessId="$accessKey" --accessKey="$secretKey" --baseURL=https://s3.us.archive.org/ --blockCacheSize=30000 --blockCacheFile="/Wreathe/.Resources/WreatheCloudService/$prefix/LocalCache" --blockSize=16M --compress=9 --blockCacheMaxDirty=256 --blockCacheWriteDelay=40000 --blockCacheThreads=2 --listBlocks --maxRetryPause=600000 --timeout=600 --encrypt --password="$passphrase" --prefix="$prefix" --size=128T --filename=StorageBlockDevice "$identifier" --defaultContentEncoding="deflate,encrypt-AES-128-CBC" --authVersion=aws2 "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/"
     sleep 60
-    losetup /dev/loop8 /Wreathe/.Resources/WreatheCloudService/$prefix/dev/StorageBlockDevice
+    losetup /dev/loop8 "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/StorageBlockDevice"
     #TODO make filessytem
     #zpool create -o relatime /dev/loop8
     ;;
 mount)
     #TODO: Check for pending jobs all done: curl "http://s3.us.archive.org/?check_limit=1&accesskey=$accessKey&bucket=$identifier"
-    s3backer --accessId="$accessKey" --accessKey="$secretKey" --baseURL=https://s3.us.archive.org/ --blockCacheSize=30000 --blockCacheFile="/Wreathe/.Resources/WreatheCloudService/$prefix/LocalCache" --blockSize=16M --compress=9 --blockCacheMaxDirty=256 --blockCacheWriteDelay=40000 --blockCacheThreads=2 --listBlocks --maxRetryPause=600000 --timeout=600 --encrypt --password="$passphrase" --prefix="$prefix" --size=128T --filename=StorageBlockDevice --debug --debug-http "$identifier" --defaultContentEncoding="deflate,encrypt-AES-128-CBC" --authVersion=aws2 -f "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/"
-    losetup /dev/loop8 "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/StorageBlockDevice"
+    #s3backer --accessId="$accessKey" --accessKey="$secretKey" --baseURL=https://s3.us.archive.org/ --blockCacheSize=30000 --blockCacheFile="/Wreathe/.Resources/WreatheCloudService/$prefix/LocalCache" --blockSize=16M --compress=9 --blockCacheMaxDirty=256 --blockCacheWriteDelay=40000 --blockCacheThreads=2 --listBlocks --maxRetryPause=600000 --timeout=600 --encrypt --password="$passphrase" --prefix="$prefix" --size=128T --filename=StorageBlockDevice --debug --debug-http "$identifier" --defaultContentEncoding="deflate,encrypt-AES-128-CBC" --authVersion=aws2 -f "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/"
+    #losetup /dev/loop8 "/Wreathe/.Resources/WreatheCloudService/$prefix/dev/StorageBlockDevice"
     #TODO: ZFS import instead
-    fsck -V /dev/loop8
-    ﻿mount -t ext4 /dev/loop8 "/Wreathe/.Resources/WreatheCloudService/$prefix/mount/"
-    ln -s "/Wreathe/.Resources/WreatheCloudService/$prefix/mount/" "$mountpoint"
+    #fsck -V /dev/loop8
+    ﻿#mount -t ext4 /dev/loop8 "/Wreathe/.Resources/WreatheCloudService/$prefix/mount/"
+    #ln -s "/Wreathe/.Resources/WreatheCloudService/$prefix/mount/" "$mountpoint"
     ;;
 attach)
     username="$1"
@@ -42,12 +42,12 @@ unmount)
     #TODO
     #umount "﻿/Wreathe/.Resources/WreatheCloudService/$prefix/dev/"
     echo "### WARNING! ### WARNING! ### WARNING! ### WARNING! ### WARNING! ###"
-    echo "Due to this issue https://github.com/archiecobbs/s3backer/"
-    echo "issues/40#issuecomment-94042115, this is not yet implemented."
+    echo "This is not yet implemented. Sorry."
     echo "### WARNING! ^^^ WARNING! ### WARNING! ### WARNING! ^^^ WARNING! ###"
     sleep 10
     #umount "https://s3.us.archive.org/$identifier/$prefix"
     #rm $mountpoint
+    exit 1
 reset)
     echo "### WARNING! ### WARNING! ### WARNING! ### WARNING! ### WARNING! ###"
     echo "If this filesystem is mounted by another system, this could cause"
